### ISSUE TITLE
euclidean_cluster package with Gazebo

### ISSUE THREAD

**Issue by huckl3b3rry87** [autowarefoundation/autoware_ai#1011]

**Comment by dejanpan** [comment]
@huckl3b3rry87 I am afraid that no-one is really using this version of gazebo to be able to help off the bet. I think that it would really make sense that completely switch to Gazebo 8 as mentioned in autowarefoundation/autoware_ai#955. We could definitely help integrating it with the current state of topics and services in Autoware.

**Comment by amc-nu** [comment]
@huckl3b3rry87 the error shown in Euclidean cluster basically means the input cloud is empty (There are no points in the received message)
I haven’t used Gazebo so I really cannot help you there.
