### ISSUE TITLE
Mapping with KITTI

### ISSUE THREAD

**Issue by aztinki** [autowarefoundation/autoware_ai#1035]

**Comment by kitsukawa** [comment]
@dlounis ndt_mapping and approximate_ndt_mapping are the same algorithm for scan matching. As I said in autowarefoundation/autoware_ai#19, they are different where to load map as reference. Regarding sample Moriyama data, the pointcloud of moriyama is collected by special measurement system called Mobile Mapping System. It is provided by other survey company. The data is not built using Autoware.
