### ISSUE TITLE
Runtime manager does not display when ./run is tried

### ISSUE THREAD

**Issue by kimjongyoung** [autowarefoundation/autoware_ai#1039]

**Comment by kimjongyoung** [comment]
Thank you so much for your help;

here is the output

bayesian@bayesian:~/Downloads/Autoware/ros$ source devel/setup.bash;
roscore & rosrun runtime_manager runtime_manager_dialog.py
[1] 5430
... logging to /home/bayesian/.ros/log/a19a23a6-d0bd-11e7-ad5d-4439c4519f9c
/roslaunch-bayesian-5430.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

Traceback (most recent call last):
  File "/home/bayesian/Downloads/Autoware/ros/src/util/packages/
runtime_manager/scripts/runtime_manager_dialog.py", line 33, in <module>
    import wx
ImportError: No module named wx
bayesian@bayesian:~/Downloads/Autoware/ros$ started roslaunch server
http://bayesian:44721/
ros_comm version 1.12.7


SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.7

NODES

auto-starting new master
process[master]: started with pid [5449]
ROS_MASTER_URI=http://bayesian:11311/

setting /run_id to a19a23a6-d0bd-11e7-ad5d-4439c4519f9c
process[rosout-1]: started with pid [5462]
started core service [/rosout]



----------------------------
Looking at the error message; ImportError: No module named wx,
I checked

bayesian@bayesian:~$ apt list --installed | grep python-wxtools

WARNING: apt does not have a stable CLI interface. Use with caution in
scripts.

python-wxtools/xenial,xenial,now 3.0.2.0+dfsg-1build1 all [installed]

**Comment by kimjongyoung** [comment]
Dear Mr. Fujii,
it says python-wxgtk3.0 is already installed.

**Comment by datnguyen82** [comment]
autowarefoundation/autoware_ai#944
