### ISSUE TITLE
lane select underlying bug.

### ISSUE THREAD

**Issue by asimay** [autowarefoundation/autoware_ai#1047]
https://github.com/CPFL/Autoware/blob/master/ros/src/computing/planning/mission/packages/lane_planner/nodes/lane_select/lane_select_core.cpp#L632

at line 627, here defined `current_lane_idx_ = -1;` , so it is always execute line 632,  always initialize lane select, never touch `processing()`.
please check.

# Bug
## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Ubuntu version:
  - ROS Version:
  - Autoware branch:

# New Feature
Describe where does new feature request come from. Add high-level picture of how the new feature should work.

**Comment by shinpei0208** [comment]
That would be appreciated if you can contribute to the repo.

@TomohitoAndo @aohsato Can you check the bug?

2017/12/09 午前10:06 "asimay" <notifications@github.com>:
