### ISSUE TITLE
errors making develop branch

### ISSUE THREAD

**Issue by dlounis** [autowarefoundation/autoware_ai#1054]
hello,

I checked out to develop branch today in order to see object detection bounding boxes. I have ubuntu 14.04 + indigo. I have also installed cuda 6.5 and ssd. I get these errors when I build autoware : 

/Autoware/ros/src/computing/perception/detection/packages/lidar_tracker/nodes/vscan_lidar_track/mainwindow.cpp:2:27: fatal error: ui_mainwindow.h: No such file or directory
 #include "ui_mainwindow.h"

make[2]: *** [computing/perception/detection/packages/lidar_tracker/CMakeFiles/vscan_lidar_track.dir/nodes/vscan_lidar_track/mainwindow.cpp.o] Error 1

make[1]: *** [computing/perception/detection/packages/lidar_tracker/CMakeFiles/vscan_lidar_track.dir/all] Error 2

make[1]: *** Waiting for unfinished jobs....

Any help ?

Thanks.

**Comment by andoh104** [comment]
Is this same issue as autowarefoundation/autoware_ai#1056 ?
If so , you'd better close this.
