### ISSUE TITLE
Build error on Ubuntu 16.04 with OpenCV 3.3

### ISSUE THREAD

**Issue by daifuku07** [autowarefoundation/autoware_ai#1070]
Fill-out only one section depending on whether you are reporting a bug or a new feature.

# Bug
## Expected Behavior
Be able to build correctly if you are using OpenCV 3.x on Ubuntu 16.04.

## Actual Behavior
https://github.com/CPFL/Autoware/blob/master/ros/src/computing/perception/detection/packages/lidar_tracker/CMakeLists.txt#L38
require module "opencv-3.2.0-dev"
So, don't work on different OpenCV 3.x version.

## Steps to Reproduce the Problem

  1. Using OpenCV 3.x (without 3.2.0)
  1. Autoware/ros/catkin_make_release

## Specifications

  - Ubuntu version: 16.04
  - ROS Version: kinetic
  - Autoware branch: master

# To do
Confirm that it works on other than OpenCV 3.2.0, change CMakeLists.txt

**Comment by sujiwo** [comment]
You can use installed OpenCV outside ROS. Just set environment variable
CMAKE_PREFIX_PATH before calling catkin or cmake.

2017-12-13 17:14 GMT+09:00 daifuku07 <notifications@github.com>:
