### ISSUE TITLE
ndt_matching doesn't work properly on GPU on Jetson TX2

### ISSUE THREAD

**Issue by TanatosSpirit** [autowarefoundation/autoware_ai#152]

**Comment by yk-fujii** [comment]
This problem seems to be a problem commonly occurring in Tegra's CUDA.
autowarefoundation/autoware_ai#153 is the same topic, so I would like to talk at autowarefoundation/autoware_ai#153

**Comment by TanatosSpirit** [comment]
@anhnv3991 no, it didn't work properly. I meant ndt_matching didn't start with block_size_x 1024 and returned an error. block_size_x had been changed to 512 before recording videos. This bug is described in autowarefoundation/autoware#1274.
