### ISSUE TITLE
Runtime Manager does not display (no module autoware_msgs.msg)

### ISSUE THREAD

**Issue by milanow** [autowarefoundation/autoware_ai#158]
Hi I am kinda new to python and linux. My system is Ubuntu 16.04

Here is the problem, when I try ./run to test out Autoware, the process manager doesn't display. And I found the issue autowarefoundation/autoware#919 , which is similar with my problem. However, when I run command "source devel/setup.bash; roscore & rosrun runtime_manager runtime_manager_dialog.py", iit reports "ImportError: No module named autoware_msgs.msg". I think my question is clear, where should I install/find out the module?

Thanks

**Comment by lijecaru** [comment]
@kitsukawa I have the same issue. When I try to run the runtime_manager, I get the error: ImportError: No module named autoware_msgs.msg. When I run catkin_make I get a CMake Error, it says: Could not find Glew (missing: GLEW_INCLUDE_DIR GLEW_LIBRARY). I checked autowarefoundation/autoware_ai#925, but I have python installed (it doesn't seem to be the problem).

@milanow did you find the solution for this issue?
