### ISSUE TITLE
Obstace_avoid  node can not avoid obstacles in a real car.

### ISSUE THREAD

**Issue by Mor-harry** [autowarefoundation/autoware_ai#170]

**Comment by marcusvinicius178** [comment]
Hi @gbiggs I am facing this harsh issue https://github.com/Autoware-AI/autoware.ai/issues/2387 for a Long time 😞

I have tried a lot off code in different machines, tested different amount off code combination/configuration, called related nodes on  launch files, modified the planners parameters, marked the checkboxes on runtime manager, debugged the topics on RQT/RVIZ/ECHO etc...

However I still was not able to solve this alone, the car does not avoid the obstacle anyway. I am sure you can give me some good advice to find a solution for A*/way_planner/safety/final waypoints distort the global planner far from obstacle.

 I have followed your comments on git, slash, ROS answers, etc and I believe you can help, you have a solid knowledge about Autoware modules. Could you please  assist me on this regard please?

Issue:
https://github.com/Autoware-AI/autoware.ai/issues/2387
