### ISSUE TITLE
"./run" in genetic x86 docker gets errors:"Failed to run /home/autoware/Autoware/ros/run_proc_manager as user root""

### ISSUE THREAD

**Issue by Patrick-Woo** [autowarefoundation/autoware_ai#171]
Fill-out only one section depending on whether you are reporting a bug or a new feature.

# Bug
I build the genetic x86 docker followed the wiki install docker Readme. after build the docker successfully, I enter the docker and press ./run.  it occurs a error message"Failed to run /home/autoware/Autoware/ros/run_proc_manager as user root". 

also in one of the green terminals, I can see another error message "(runtime_manager_dialog.py:174): Gdk-CRITICAL **: IA__gdk_color_free: assertion 'color != NULL' failed"
![screenshot from 2018-05-30 08-53-55](https://user-images.githubusercontent.com/24869702/40693081-0f505b6e-63e8-11e8-8748-271aa5896872.png)

## Steps to Reproduce the Problem

  1.build the x86 docker 
  2.Autoware Docker Setup with case 2 method:   sudo sh build.sh kinetic
  3.sudo sh run.sh kinetic
  4. cd Autoware/ros
  5.    ./run
  6. get errors mentioned above

## Specifications

  - Ubuntu version:ubuntu16.04.1 LTS
  - ROS version: kentic
  - Autoware branch: master

**Comment by filiperinaldi** [comment]
This issue is a duplicate of autowarefoundation/autoware_ai#205. Although this issue is older by a few days, the other issue is more precise with regards the error. I suggest someone (@kfunaoka, @amc-nu ?) to close this issue as duplicated.
