### ISSUE TITLE
obstacle simulation 

### ISSUE THREAD

**Issue by munirfarzeen** [autowarefoundation/autoware_ai#184]
Hi, 
I am trying to simulate obstacle avoidance using the ros bag provided. 
how to create obstacle in riviz so that, they can be detected.

**Comment by hakuturu583** [comment]
I think it is impossible to simulate obstacle avoid test from rosbag data.
I am trying to integrate with LGSVL Simulator with Autoware.
autowarefoundation/autoware_ai#421 
Please wait a bit!!
