### ISSUE TITLE
[Discussion] Naming convention of topic name and msg type for v2.0

### ISSUE THREAD

**Issue by kfunaoka** [autowarefoundation/autoware_ai#237]

**Comment by LukePhairatt** [comment]
Hi Kinji, I got some ideas and hope it is somewhat useful.
1- Including ‘Array’ at the end of the message type as indicated in the diagram.
    ‘ObjectArray’

2- Including ‘Array’ at the end of the topic name. ‘/detected_objects_vision_array’ but limited to 4    
    words
    
    These 1&2 will align with what already used in Autoware for example
    Message Type: autoware_msgs/LaneArray
    Topic Name: "/lane_waypoints_array"

3- ‘autoware_msgs’ namespace
    Could we be more specific about the message type as defined in ROS? 
    For example ‘geometry_msgs/TwistStamped’
    so we can define autoware specific messages to something like ‘autoware_(xxx)_msgs/xxxx’
    for example ‘autoware_paths_msgs/LaneArray’
    or something along this idea.            

4- Capital word of the type name such as geometry_msgs/TwistStamped 
    Not all are like that at the moment such as ‘autoware_msgs/lane’

5- ‘Topic’ naming convention?
     for example /ParentNode_ChildNode_DataName
                         /detection_vision_object_array
                         /detection_lidar_object_array
                         /detection_fusion_object_array
                         /detection_combined_object_array
                         /detection_tracked_object_array
 
     or else relative namespace e.g. detection/vision_object_array

**Comment by kfunaoka** [comment]
@LukePhairatt Thank you for the beneficial advice. I've updated the component diagram as 2nd draft thanks to you.

<img width="550" alt="2018-08-01 12 45 10" src="https://user-images.githubusercontent.com/38030772/43500108-dbe7a948-9589-11e8-80c7-8c5c307eabe6.png">

Generated from https://github.com/CPFL/Autoware/tree/feature/architecture/docs/architecture

> 2- Including ‘Array’ at the end of the topic name. ‘/detected_objects_vision_array’ but limited to 4
words

I think “_array” at the end of topic name is not a good idea because it simply represents type. Similar to dataname_int. So I removed the “_array” in this 2nd draft.

**Comment by LukePhairatt** [comment]
@kfunaoka Looks good. Yes agreed with you on this. "_array” at the end of topic name is not a good idea because it simply represents type."

I proposed this _array concatenation just because it will in line with other topics such as "lane_waypoints_array". But it is better without it.
