### ISSUE TITLE
ndt_mapping doesn't work fine

### ISSUE THREAD

**Issue by hamkuchan** [autowarefoundation/autoware_ai#280]

**Comment by ajay1606** [comment]
@kitsukawa I am sorry to say this, Now also am unable to find the files in Autoware/ros/ and Shome/.ros/ Both of the locations.
Even though I have changed save locations also, I am unable to find the files. 
Also in the PR autowarefoundation/autoware_ai#890, I understood that the default location is in Home/.ros/, 

Sincerely, looking for your help 
Kind Regards,
Ajay
