### ISSUE TITLE
Unable to find image 'autoware/autoware:1.8.0-kinetic' locally docker: Error response from daemon: manifest for autoware/autoware:1.8.0-kinetic not found.

### ISSUE THREAD

**Issue by lonfr** [autowarefoundation/autoware_ai#313]

**Comment by lonfr** [comment]
According to your suggestion,this problem is solved,Thank you!

ziyi.wang <notifications@github.com> 于2018年9月25日周二 下午8:12写道：

**Comment by yuqli** [comment]
Wow thanks so much for the response. I wasn’t expecting anyone to really notice... thanks!
