### ISSUE TITLE
Error in launching Rviz from Autoware Docker

### ISSUE THREAD

**Issue by KetkiChaudhary** [autowarefoundation/autoware_ai#359]

**Comment by ajay1606** [comment]
> I had the same issue, too. It is related to using nvidia-docker2. There is an open PR to solve this problem.
> 
> autowarefoundation/autoware#1416
> 
> Steps: Replace build.sh and run.sh files (+ created Dockerfile.nvidia-docker-v2) with the ones in the PR. or just merge PR into your branch.

Thank you so much for your kind response. Much appreciated. it worked for me.
