### ISSUE TITLE
Autoware ROS Interface to Low Level Controllers

### ISSUE THREAD

**Issue by aohsato** [autowarefoundation/autoware_ai#396]

**Comment by aohsato** [comment]
@hatem-darweesh Greatly thanks for your suggestion! Your abstraction class design for vehicle communication seems to be in Actuation Node, so perhaps your topic is more suitable for autowarefoundation/autoware_ai#316, Dejan said.
And in this post, would you please see and comment to my ROS topic and param design for communication with Actuation Node?

**Comment by kfunaoka** [comment]
@aohsato I'd like to formalize your proposal into an abstract based on [Overview](https://github.com/CPFL/Autoware/wiki/Overview#motion) and the level of autowarefoundation/autoware_ai#288. Since this issue targets the flow after High Level Planner (velocity_planner and trajectory_planner here), I'm creating a diagram that also focus on the flow. This figure is not incomplete. Since I'm not familiar with motion planning, I'd like to discuss with F2F at first :)

![componentdiagram](https://user-images.githubusercontent.com/38030772/48033877-80663900-e1a0-11e8-828e-5f0441801cf2.png)

**Comment by dejanpan** [comment]
@aohsato: 

> @dejanpan Just as you said, this post title is a little bit wrong so I changed. Thanks much.
> Yes I read that post and I understood "ROS2 Vehicle Node" generated based on "Vehicle Abstraction Class" performs as "Actuation Node" in my figure. Is this correct?

In autowarefoundation/autoware_ai#316 we abstract the vehicle (DBW interface and CAN messages) which makes autowarefoundation/autoware_ai#316 be the closest SW to the car interface. In you figure you have Low Level Controller between the Actuation Node and the car which does not make sense (or I do not know what kind of Low Level Controller) are you talking about. But I assume that this Low Level Controller will be written in ROS, will receive desired speed and curvature and it will output to the vehicle throttle/break and acceleration, right?

> 
> And next, I want to design around Planning and Control too. Of course, I agree.
> So in this issue, I want to decide the architecture after local planner (publishing waypoints including speed and pose, `velocity_set` in current Autoware), especially message definition for Actuation Node. Please help?

I can help but we need to break the old Autoware architecture. Could we maybe start by defining which inputs/outputs go into these 4 layers and what the respective algorithms in these 4 layers would be?

1. Global planning
2. Behaviour planning
3. Local planning
4. Control

If you want, I will ask Chris for a slightly more detailed architecture tomorrow.

**Comment by kfunaoka** [comment]
@aohsato I guess motion planning layer will be defined in autowarefoundation/autoware_ai#419. The slide defines actuation layer and its input and outputs. The motion planning layer, e.g., motion planner and motion controller, in this slide is just an example. Is my understanding correct?
