### ISSUE TITLE
Point cloud visible with RViz but invisible with calibration toolkit

### ISSUE THREAD

**Issue by wsung1** [autowarefoundation/autoware_ai#40]

**Comment by QipiaoZhou** [comment]
> Did you try to use WASD and QE to change the pose of the viewport?
> If you click the 3D viewport and push 'S' key to move backward, you will see an RGB XYZ-axis. That means the GLViewer works fine. Then please change the background to check where the points are.
> Thanks!

after pushing “s”，i canot see xyz axis，what can i do then
