### ISSUE TITLE
[Feature] LGSVL Simulator Integration design.

### ISSUE THREAD

**Issue by hakuturu583** [autowarefoundation/autoware_ai#421]

**Comment by hadiTab** [comment]
@dejanpan we have been in touch with the Autoware team and have been collecting requirements and developing features required for this integration. We consider the simulator to be a work in progress and appreciate all the feedback we can get which will be taken into account for future development.

At the moment the simulator runs as a GUI application, either on the developer’s machine or on another machine. Moving forward we may add other modes of operation based on requirements. We understand that it would be useful to be able to test individual modules with the simulator and supporting this is on our road-map (i.e. providing ground truth data). I believe much of the requirements you have proposed fall into this category.

As for the Autoware fork we are maintaining on github, it includes modifications intended to facilitate the use of Autoware with the simulator. With the integration proposed here users should be able to use the simulator with the official Autoware repository.

**Comment by andytolst** [comment]
@hakuturu583 we are still discussing what’s the best way of providing initial position.
Setting arbitrary x,y in virtual world coordinate system is easy, but it could easily lead to placing the car inside the building, and there is no easy way to know coordinates without launching Unity editor.

UTM or lay/lon makes more sense IMO, but it has its own complications
