### ISSUE TITLE
Selecting image topic in calibration_publisher node

### ISSUE THREAD

**Issue by mitsudome-r** [autowarefoundation/autoware_ai#425]

**Comment by amc-nu** [comment]
Yes I agree. RTM needs to be changed. That combo box allows to launch a publisher for each namespace..

> I thought CameraInfo values are static and doesn't really need any synchronization.

You’re right values should not change., However, time stamp should be updated. Calibration methods, and fusion methods require image and intrinsic topics to be synced. 
For instance, fusion only reads intrinsics(like you mentioned ), but also tf and detection results. If the intrinsics are latched then there is no trigger from the image side and, the time stamp cannot be matched with the corresponding tf and the detection results from image and lidar.
This is a simple and real example.
