### ISSUE TITLE
[Bug] The maximum speed becomes a negative value according to the angular velocity.

### ISSUE THREAD

**Issue by yn-mrse** [autowarefoundation/autoware_ai#473]
# Bug
## Expected Behavior
The sign of the maximum speed does not depend on the angular velocity and needs to be the same as the current speed.

## Actual Behavior
The maximum speed becomes a negative value according to the angular velocity.

[`double max_v = g_lateral_accel_limit / omega;`](https://github.com/CPFL/Autoware/blob/develop/ros/src/computing/planning/motion/packages/waypoint_follower/nodes/twist_filter/twist_filter.cpp#L69)
It is necessary to rewrite the above link as follows.
`double max_v = g_lateral_accel_limit / fabs(omega);`

**Comment by YamatoAndo** [comment]
autowarefoundation/autoware_ai#133 is opened about this bug
