### ISSUE TITLE
Add missing install target to all packages that produce libraries or executables

### ISSUE THREAD

**Issue by esteve** [autowarefoundation/autoware_ai#491]

**Comment by sgermanserrano** [comment]
This ties in together with autowarefoundation/autoware_ai#475 as some of the listed packages are classified as obsolete in the [spreadsheet](https://docs.google.com/spreadsheets/d/1wcMiQJFr3SwHAS9H21UbcmnmMMDvq04Jpa7uGml0MdI/edit)

**Comment by amc-nu** [comment]
It’s worth noting that not only the install command associated to the library or executable is necessary, but also the launch files, configuration files, or any other external files.
We need your kind cooperation 
@aohsato @kitsukawa @messi49 @h-ohta @alexandrx @drwnz @jacoblambert @shinpei0208 @yukkysaito @yk-fujii @hakuturu583 @cirpue49 @daifuku07 @isamu-takagi 
Only each one of you know which files are required in your nodes.

**Comment by amc-nu** [comment]
fixed on autowarefoundation/autoware#1861
