### ISSUE TITLE
[Discussion] Map Architecture

### ISSUE THREAD

**Issue by kfunaoka** [autowarefoundation/autoware_ai#529]

**Comment by msmcconnell** [comment]
A map abstraction layer is a great idea!  Are you looking to define the API in this issue as well, or just propose the creation of such an API?

I think there may be some overlap with autowarefoundation/autoware_ai#408 as the definition of unique lane id's will be determined by the vector map specification standard (Autoware format, lanelet2, etc.) It might be best to pick one representation to use in ros messages, but allow the underlying internal structures to be swapped out as you suggest.

**Comment by mitsudome-r** [comment]
The format proposed in autowarefoundation/autoware_ai#408 should contain most of commonly used information in Autoware and should contain less "unwanted" information (since that how it was made). Maybe internal representation can start with something similar to the format and extend it to add any valuable features from other formats.

**Comment by msmcconnell** [comment]
@mitsudome-r 
LaneLet2 does provide center line calculations per documentation https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/master/lanelet2_core/doc/LaneletPrimitives.md
```
lanelets may have an additional centerline to guide the vehicle. This centerline must be within the area formed by the left and right bound and must not touch the boundaries. If no centerline is given, the library will calculate it for you.
```
However, the key for an interface like that proposed above is how we represent the lane geometry and connections in ROS messages. I believe that the description should match one of the standards presented in autowarefoundation/autoware_ai#408. This ensures that all users have a clearly defined way of interpreting the data. Regardless of which file format or processing component is actually used for map data, a single interface representation should be selected to describe the road in the abstract.
