### ISSUE TITLE
Build Autoware on PX2, and link Nvidia Driveworks API target, but Error for: dw/core/Context.h: No such file or directory

### ISSUE THREAD

**Issue by majichang** [autowarefoundation/autoware_ai#558]
[ 56%] Built target bond_generate_messages_cpp
Scanning dependencies of target nodelet_generate_messages_eus
[ 56%] Built target nodelet_generate_messages_eus
Scanning dependencies of target bond_generate_messages_eus
[ 56%] Built target bond_generate_messages_eus
Scanning dependencies of target autoware_driveworks_gmsl_interface_node
[ 56%] Building CXX object driveworks/packages/autoware_driveworks_gmsl_interface/CMakeFiles/autoware_driveworks_gmsl_interface_node.dir/src/gmsl_camera_multiple/gmsl_node.cpp.o
In file included from /home/nvidia/Autoware/ros/src/driveworks/packages/autoware_driveworks_gmsl_interface/include/SekonixGmslCamera.hpp:71:0,
                 from /home/nvidia/Autoware/ros/src/driveworks/packages/autoware_driveworks_gmsl_interface/src/gmsl_camera_multiple/gmsl_node.cpp:40:
/home/nvidia/Autoware/ros/src/driveworks/packages/autoware_driveworks_gmsl_interface/include/DriveWorksApi.hpp:66:29: fatal error: dw/core/Context.h: No such file or directory
compilation terminated.
driveworks/packages/autoware_driveworks_gmsl_interface/CMakeFiles/autoware_driveworks_gmsl_interface_node.dir/build.make:62: recipe for target '

**Comment by majichang1990** [comment]
@duclinhfetel

yeah， I had successed install driveworks-0.3 on PX2，and the path is /usr/local/driveworks

**Comment by filiperinaldi** [comment]
This is the same error on the recent issue autowarefoundation/autoware_ai#549.
Perhaps FindDriveWorksSDK.cmake should fail earlier.
