### ISSUE TITLE
upgrade gmsl camera driver to DriveWorks 1.5 on NVIDIA DRIVE Platform

### ISSUE THREAD

**Issue by twbabyduck** [autowarefoundation/autoware_ai#614]
## Status
I would like to do a pull request; however, I am not quite understand the contributing guidelines and the workflow of the process. Does anyone could guide me through this?

## Specification

  - Ubuntu version : 16.04.x
  - ROS version : Kinetic Kame
  - DriveWorks version : 1.5+
  - Target Platform : NVIDIA DRIVE AGX Xavier, NVIDIA DRIVE AGX Pegasus

# New Feature
Upgrade `autoware_driveworks_gmsl_interface` && `autoware_driveworks_interface` to the latest DriveWorks API version (e.g. 1.5) 

### Future Release

- remove all the deprecated API, related files and references
- support up to 16 cameras (4 camera ports) for DRIVE™ AGX Developer System

**Comment by jokla** [comment]
Hi @twbabyduck, 

As @amc-nu suggested, could you create the PR without the docker support? Or create a public fork of Autoware with your modification? This would be helpful for the community. 

I didn't find any clear instructions on how to use docker on the PX2. There was a script but it is not working anymore.  autowarefoundation/autoware_ai#526 

If you want to use the docker you should install Driveworks inside the docker or you should link the libraries from the host (easier but not very clean method).
See here for some references:
- [Installing Driveworks within a docker image](https://devtalk.nvidia.com/default/topic/1030912/faq/installing-driveworks-within-a-docker-image/
)
- [DriveInstall ](https://devtalk.nvidia.com/default/topic/1043762/driveworks/driveinstall-stuck-when-customizing-packages-installation-/?offset=2#5296679)

Nvidia-docker is not compatible with PX2. If you want to use the GPUs, you should also add the following instructions when you run the docker:
`--device=/dev/nvhost-ctrl --device=/dev/nvhost-ctrl-gpu --device=/dev/nvhost-prof-gpu --device=/dev/nvmap --device=/dev/nvhost-gpu --device=/dev/nvhost-as-gpu --device /dev/nvgpu-pci `
