### ISSUE TITLE
Correct building process

### ISSUE THREAD

**Issue by syohex** [autowarefoundation/autoware_ai#675]
- [ ] Fix cycle dependency issues
- [ ] Declare package dependency correctly. Some dependencies are not declared for avoiding build errors now.
- [ ] Remove build warnings. There are some build warnings about rostest and roslaunch.

CC: @manato @yukikitsukawa @syouji

**Comment by shinpei0208** [comment]
Let's rewrite the code in Autoware version 2. We plan to redesign GUI as
well. Usuda-san, please list this up in TODO work.
2016/02/02 18:41 "Syohei YOSHIDA" notifications@github.com:

**Comment by syohex** [comment]
Sorry I write Japanese at first.

### パッケージ間の依存を増やさないための注意

#### ライブラリのヘッダファイルで messageから生成されるヘッダファイルを includeしない

関連する関数を使わないパッケージでも, それを includeしてしまうと, その messageを生成するパッケージに依存してしまうことになる.

#### ライブラリで messageから生成されるヘッダファイルを includeしない

それをリンクするパッケージが間接的に messageを生成するパッケージに依存してしまう. メッセージで渡ってきたデータの処理をライブラリに切り出したい場合は, メッセージの中のデータを渡すようにするなどする(std::vector型等). もしくは別途定義したメッセージに依存しない class, struct移し替える等する

#### むやみにライブラリに切り出さない

汎用的なもの以外は切り出さない方がいい. パッケージ間の依存を返って高めてしまう可能性がある. 別パッケージにするほど有用かをまず考える.

#### その他気になったところ

##### ライブラリにグローバル変数がある
- ライブラリが状態を持つ
  - 複数スレッドで使えるのか
  - 状態を引数として渡すようにできるかを検討する

##### ライブラリ関数の引数がない, 戻り値が void
-  何のために呼び出している ?
- ライブラリの状態を変化させている ?
- ライブラリ関数としては引数だけに依存するものが望ましい.

#### 名前が適当すぎる
- namespaceを使う or ライブラリの prefixをつける
