### ISSUE TITLE
Processor load info missing

### ISSUE THREAD

**Issue by rg4444** [autowarefoundation/autoware_ai#810]
We running Autoware on several different Ubuntu 14.04, ROS Indigo hosts, and none of them display real-time processor load, as seen on demo videos.
Installation done as described in instruction. 
Whet we are missing, or this functionality is not included in GitHub source?

![autoeware2](https://cloud.githubusercontent.com/assets/16691942/14064717/a773954e-f416-11e5-805f-0cd9cc89cad3.png)
![autoware1](https://cloud.githubusercontent.com/assets/16691942/14064716/a76f9264-f416-11e5-9603-d8834bf53f82.png)

**Comment by syohex** [comment]
Sorry I use Japanese in this comment.

@kondoh2 `top`コマンドの解析箇所が localeにより例外が発生してしまっています. スペイン方式(`de_DE.UTF-8`等)だと小数点数の表示形式が `123,45`(小数点がカンマ)となり, これを Pythonの `float`関数に与えると例外が発生します(Pythonの `float`関数は英米方式 `123.45`しか受け付けない). 解決方法としては下記の URLのようにカンマをピリオドで置き換える, `float`でなく `locale`パッケージの `atof`関数を使う, `top`コマンドを `LC_ALL=C`等で実行する方法が考えられます. `float`が使われている箇所が複数存在し, 私では理解が及ばない部分もありますので, 修正案を検討いただければと思います. よろしくお願いします.

http://stackoverflow.com/questions/6633523/how-can-i-convert-a-string-with-dot-and-comma-into-a-float-number-in-python

**Comment by kondoh2** [comment]
ご指摘ありがとうございます。
了解です。
検討します。

2016年4月1日 17:31 Syohei YOSHIDA notifications@github.com:
