### ISSUE TITLE
Custom Vector map creation

### ISSUE THREAD

**Issue by rg4444** [autowarefoundation/autoware_ai#811]

**Comment by nsakar** [comment]
Can you provide some instructions on how to create a vector map with landmarks and lane marks?

I have been able to generate a path via waypoint saver but not a vector map of landmarks.

Regards

Nandini

**Comment by shinpei0208** [comment]
We don't have a function to create a vector map. We ask a map company to
construct it for us. Having said that, there is some work in progress to
create a vector map by Autoware itself, though the timeline of milestones
is not clear yet.

2016-05-19 1:30 GMT+09:00 nsakar notifications@github.com:

**Comment by nsakar** [comment]
Thank you
