### ISSUE TITLE
How to connect Autoware to the vehicle's CAN network?

### ISSUE THREAD

**Issue by sgzzgit** [autowarefoundation/autoware_ai#817]
To date, I have finished ndt_mapping and ndt_matching already.
Now my next plan is to apply the localization and mission result to the vehicle. My vehicle could be driven via the can network already.

However ,I get the following questions:
1.Could Autoware output the motion planning result via can network to control the vehicle?
2.Could Autoware output the localization result via socket or serial port?
3.which type of can interface card that Autoware support? Does it support Vector VN1630A?

Thanks a lot, and if there is anything that I can do for your team ,Please contact me, I will try my best to  do it well and contribute my own strength.

**Comment by shinpei0208** [comment]
Hi, Japan has long holidays now. Pls wait for a few days.
2016/05/05 15:01 "sgzzgit" notifications@github.com:

**Comment by nsakar** [comment]
Can you tell me the units of measure of the twist cmd rostopic published by pure pursuit algorithm.

Is linear acceleration is meters.sev , kilonmeteres per second [ or minute, hour]?

What is the unit of measure of angular orientation velocity [ radians per sec or degree per sec]  ?

I am attempting to integrate the Autoware stack with a ros driver for another car that accepts linear x is kilometers per hor and angular velocity in radians per sec.

Regards

Nandini
