### ISSUE TITLE
which type of camera does autoware use?

### ISSUE THREAD

**Issue by sgzzgit** [autowarefoundation/autoware_ai#822]
Thanks in advance.
In the autoware's video , It could detect the Pedestrian and traffic signal. Could you tell me how many cameras does autoware use and whta is the type of the camera?
Thanks again.

**Comment by shinpei0208** [comment]
We use at least two cameras. One dedicated for traffic light recognition
and the other used for generic detection.
2016/05/12 10:18 "sgzzgit" notifications@github.com:

**Comment by shinpei0208** [comment]
We don't select cameras. Up to your preference. You just need a driver. By
default we support drivers for PointGrey Glasshopper/LadyBug, Baumer, and
generic USB cameras such as webcams.
2016/05/12 10:30 "sgzzgit" notifications@github.com:

**Comment by nsakar** [comment]
How are the imaging algorithms integrated into Mission and motion planning?
Is the motion planning using the pedestrian detection or traffic light detection at all?

How does motion planning know that it needs to avoid collision with objects or stop at traffic light?

I have the following graph for enabling motion planning:

[cid:image001.jpg@01D1ABB6.832A4C80]

**Comment by nsakar** [comment]
Please find attached graph. I would like to know how to add object recognition and traffic sign/ light detection into mission/motion planning flow.

Regards

Nandini

**Comment by nsakar** [comment]
Which branch has the integration of obj_reproj with motion planning is progress?
