### ISSUE TITLE
How to navigate in a larger place

### ISSUE THREAD

**Issue by sgzzgit** [autowarefoundation/autoware_ai#831]

**Comment by shinpei0208** [comment]
Yes, and RGB information. Beyond pointcloud, it contains vector objects,
such as zebra zones, traffic lights, lanes, lines, and road networks. They
are all collections of position data (x, y, z). See:
https://youtu.be/yOEro_GChoM

Here is a link to the map company.
http://www.aisantec.co.jp/english/
2016/05/27 19:10 "sgzzgit" notifications@github.com:
