### ISSUE TITLE
How to debug latency issues between Autoware stack and car ros driver

### ISSUE THREAD

**Issue by nsakar** [autowarefoundation/autoware_ai#833]

**Comment by nsakar** [comment]
In simulation, it drives smoothly

Regards

Nandini

**Comment by nsakar** [comment]
Yes. I solved this by setting vehiclFollowing flag in calcTwist to false. That in turn made the twist commands to be computed everytime. And solved my problem.

Regards

Nandini

**Comment by nsakar** [comment]
Yes. I had to set vehicleFollowing to false.

Regards

Nandini

**Comment by nsakar** [comment]
verifyFollowing sorry

**Comment by nsakar** [comment]
Line 512:

Bool following_flag = false;

**Comment by nsakar** [comment]
What velocity have you set your waypoints at in your trajectory? At higher velocities I find there is over or under steering. I am assuming  ndt matching is not fast enough to conduct localization at higher velocities. Can anyone answer the question?

**Comment by nsakar** [comment]
20 kph.  The  trajectory velocity is in kph.

**Comment by nsakar** [comment]
I am getting this issue when attempting to integrate object detection into velocity set using points_cluster.

Regards

Nandini

**Comment by nsakar** [comment]
I use lidar and Euclidean clustering.

Have you integrated object detection with velocity_set?

**Comment by nsakar** [comment]
Thank you…

**Comment by shinpei0208** [comment]
Euclidean clustering may not be suitable for the real time use. We often
use virtual scan.

For steering, perhaps it is a controller issue inside the physical vehicle,
not on the Autoware front. This is what often happens to us when using a
real vehicle.
2016/06/27 15:47 "nsakar" notifications@github.com:

**Comment by xiaohedu** [comment]
@sgzzgit  Hi , I am doing fusion detecting multi-objects with one camera and mm-wave radar sensor , can you share some experiences about it （especially joint-calibration between camera and radar ）？
