### ISSUE TITLE
How to implement vehicle following and vehicle passing using Autoware stack

### ISSUE THREAD

**Issue by nsakar** [autowarefoundation/autoware_ai#837]

**Comment by nsakar** [comment]
yes

**Comment by nsakar** [comment]
I would like an answer to the question.

Regards

Nandini

**Comment by nsakar** [comment]
Vehicle following and collision avoidance using vscan points : Yes

Vehicle passing : No. Need more information.

**Comment by nsakar** [comment]
Yes. I  am able to detect all obstacles that are within detection range of waypoints and within height interval [ hc – hf]
I need more info on the ceiling and floor height settings. Is this from the ground or from the localizer pose?
By default it set to +2 , -2. Is this in meters and from ground plane as 0? Or localizer pose plane as 0? I am presuming the heights are on the z axis.

**Comment by shinpei0208** [comment]
@alexanderhmw, are you online?
2016/07/10 10:08 "thomas3016" notifications@github.com:

**Comment by alexanderhmw** [comment]
Hi Kato-sensei , i am traveling now. I will add comment to vscan soon after getting back

**Comment by shinpei0208** [comment]
Thx!
2016/07/10 22:49 "HMW-Alexander" notifications@github.com:
