### ISSUE TITLE
Runtime manager error

### ISSUE THREAD

**Issue by anhnv3991** [autowarefoundation/autoware_ai#838]

**Comment by kondoh2** [comment]
おそらくRuntime Managerから起動したコマンドのいづれかが、標準出力あるいは標準エラー出力へ、
0xcd という値の文字を出力した事による現象と思われます
。
Runtime Managerは起動したコマンドの出力する文字を拾ってStatusタブのGUIに表示しようとします。
そこでGUIの部品にとって不正な文字コードの判定にひっかかってるようです。
GUI部品は0x7f以下の値を期待しています。

起動コマンド側の出力箇所は特定できてませんが、Runtime Manager側で0x80以上の値を無視する対応を入れる事は可能です。

**Comment by kuriking** [comment]
ごめんなさい、ヘッダのバイナリをそのまま出力している箇所があります。

**Comment by shinpei0208** [comment]
修正お願いします。

2015-09-14 16:18 GMT+09:00 USUDA Hisashi notifications@github.com:

**Comment by kuriking** [comment]
@anhnv3991 
申し訳ございません、修正しました。お手数ですが、確認をお願いいたします。

**Comment by syohex** [comment]
@anhnv3991 まだ問題が起きているでしょうか ? 問題が発生しなくなったら issueの closeをお願いします.

**Comment by amc-nu** [comment]
Yosh-san

Please look at the CV_tracker specially range fusion and its library, under computing, perception.

Greetings

Syohei YOSHIDA さんは書きました :
