### ISSUE TITLE
Points2Vscan

### ISSUE THREAD

**Issue by nsakar** [autowarefoundation/autoware_ai#842]

**Comment by nsakar** [comment]
Is it possible to simply view the vscan points without a camera?  I can see that /vscan_points are being generated when I invoke the following:

rosrun points2image points2vscan

**Comment by nsakar** [comment]
Yes. I just realized that.. ☺ Thank you…

One more question. I will be using the vscan_points to detect obstacles for my velocity_set node…

I see a bunch of parameters hard coded into the points2vscan node. Will it be sufficient to configure the velocity_set node using /config/velocity_set ros topic for my roof top lidar to detect obstacles?

Regards

Nandini

**Comment by nsakar** [comment]
Can you please explain the algorithm used to compute vscan points from points_raw? How is the down sampling done and is it lossless from an obstacle detection perspective?

Regards

Nandini

**Comment by alexanderhmw** [comment]
Hi Nandini,

Our algorithm refers to the paper "robust virtual scan for obstacle
detection in Urban environments" IEEE Intelligent Vehicles Symposium 2016.
Please check it for more details.

Best,
HMW-Alexander

**Comment by nsakar** [comment]
Thank you
