### ISSUE TITLE
Split big map into smaller pcd files 

### ISSUE THREAD

**Issue by Benjaminmar8** [autowarefoundation/autoware_ai#861]
I understand that the question has been discussed here autowarefoundation/autoware_ai#830 . However, the answer was not conclusive to me. I have a big bag file and it has been split into several smaller bag files. I can produce pcd files from the these smaller bag files. Based on the discussion of autowarefoundation/autoware_ai#830 , I will need to transform pcd files manually. 
Here is my question: how do I transform the pcd files. Assuming I have pcd1 and pcd2, what I am thinking is that I use ndt of PCL to determine the rigid transformation between pcd1 and pcd2, and then apply the transformation to pcd2 and save it as a new pcd (transformed pcd). Is this approach correct? Thanks a lot for the help.

**Comment by yiakwy** [comment]
Please see my discussion:
https://github.com/PointCloudLibrary/pcl/issues/2652

Yuki Kitsukawa <notifications@github.com> 于2018年11月26日周一 下午1:15写道：
