### ISSUE TITLE
Is NDT-mapping able to do loop clousre? 

### ISSUE THREAD

**Issue by Benjaminmar8** [autowarefoundation/autoware_ai#870]

**Comment by shinpei0208** [comment]
No, it does not support loop closing now. We are adding that capability.
Thus, the map of 1km long must include errors. We suggest users to get a
map from the map company, if a large area is needed.

2016/09/24 午後1:36 "sgzzgit" notifications@github.com:

**Comment by shinpei0208** [comment]
ndt_mapping, as it is, does not support loop closing. Therefore, it
accumulates errors while mapping. Assume for example that an error of 0.1cm
is accumulated every 1m distance. If the distance of map is short, errors
are small. But if it goes over a few kilometers, errors cannot be ignored.
Under the above assumption, 1km distance of map could include 1m error.
Loop closing would solve this problem.

2016/09/24 午後9:52 "sgzzgit" notifications@github.com:

**Comment by kfunaoka** [comment]
Registered as enhancement at autowarefoundation/autoware_ai#203
