### ISSUE TITLE
what does tku stands for?

### ISSUE THREAD

**Issue by Benjaminmar8** [autowarefoundation/autoware_ai#903]
Hi, All,
I noticed that there is ndt_mapping_tku in the code. What does tku stands for? is it a NVidia GPU? Thanks.

**Comment by shinpei0208** [comment]
The name of the author - Prof. Takeuch.

2017/02/07 午後3:20 "Benjaminmar8" <notifications@github.com>:

**Comment by shinpei0208** [comment]
the same algorithm but tku is more suitable for CUDA coding while pcl
include a lot of library function calls and they prevent us from CUDA
coding.

2017-02-07 18:36 GMT+09:00 Benjaminmar8 <notifications@github.com>:
