### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by hriapatil** [autowarefoundation/autoware_ai#923]
1. nvcc fatal   : Stray '"' character
CMake Error at rbsspfvehicletracker_generated_rbsspfvehicletracker.cu.o.Release.cmake:222 (message):
  Error generating  /home/apatil/Autoware/ros/build/computing/perception/detection/packages/lidar_tracker/CMakeFiles/rbsspfvehicletracker.dir/nodes/vscan_lidar_track/./rbsspfvehicletracker_generated_rbsspfvehicletracker.cu.o

2. /usr/bin/ld: cannot find -lDummyDevice
/usr/bin/ld: cannot find -lOniFile
/usr/bin/ld: cannot find -lPS1080

**Comment by amc-nu** [comment]
solved on autowarefoundation/autoware_ai#1036
