### ISSUE TITLE
Compile error:" make: INTERNAL: Exiting with 10 jobserver tokens available; should be 8! Invoking "make -j8 -l8" failed "

### ISSUE THREAD

**Issue by MrYuJing** [autowarefoundation/autoware_ai#927]
Hello!
When I reach these instructions section "How to build" on the web page "https://github.com/CPFL/Autoware" and then other command are done success but the last one "./catkin_make_release " failed. Something wrong like this:
"
[ 65%] Building CXX object computing/perception/localization/packages/orb_localizer/CMakeFiles/orb_mapping.dir/nodes/common.cpp.o
The bug is not reproducible, so it is likely a hardware or OS problem.
make[2]: *** [computing/perception/localization/packages/orb_localizer/CMakeFiles/orb_matching.dir/nodes/orb_matching/orb_matching.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
Linking CXX executable /home/yj/Autoware/ros/devel/lib/orb_localizer/orb_mapping_offline
[ 65%] Built target orb_mapping_offline
make[1]: *** [computing/perception/localization/packages/orb_localizer/CMakeFiles/orb_matching.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Linking CXX executable /home/yj/Autoware/ros/devel/lib/orb_localizer/orb_mapping
[ 65%] Built target orb_mapping
make: *** [all] Error 2
make: INTERNAL: Exiting with 10 jobserver tokens available; should be 8!
Invoking "make -j8 -l8" failed
"
Can anyone here help me fix it out? Thanks a lot!

**Comment by sujiwo** [comment]
Could you specify OS and ROS version you use?

2017-06-13 11:57 GMT+09:00 MrYuJing <notifications@github.com>:
