### ISSUE TITLE
Any tips on using calibration toolkit?

### ISSUE THREAD

**Issue by Codebot2455** [autowarefoundation/autoware_ai#939]

**Comment by Codebot2455** [comment]
@dejanpan I would greatly appreciate any help possible.

I have watched that video numerous times.

I am using a Velodyne VLP16 and a Pointgrey Flea3 camera with a wide angle lens.

Do you know if I'm supposed to calibrate the camera by itself before doing the `Camera -> Velodyne` calibration? Should I use the Autoware camera calibration or the ROS camera_calibration package?

I noticed from the discussion between @Eric-Gonzalez and @alexanderhmw on issue autowarefoundation/autoware_ai#882 that Eric published `/camera/camera_info` when doing `Camera -> Velodyne`. Is this required(the readme doesn't mention it)?

Also how many Velodyne/Camera 'Grab' readings should I do?

THANK YOU!!!!

**Comment by amc-nu** [comment]
Please try new calibration tool. autowarefoundation/autoware#1131
