### ISSUE TITLE
Runtime manager not starting

### ISSUE THREAD

**Issue by iulialexandra** [autowarefoundation/autoware_ai#944]

**Comment by dejanpan** [comment]
Which ROS Version are you using and which branch did you check out and
compile (best give us commit sha).

What you need to type in is your root user password.

**Comment by manato** [comment]
@iulialexandra 
This problem sometimes happens by lack of some python dependencies.
Would you refer autowarefoundation/autoware_ai#925 ?
Conversations here may help you to find out what the exactly problem is.

**Comment by iulialexandra** [comment]
Thanks to all for your answers, it works now. I had the same issue as autowarefoundation/autoware_ai#925, but I hadn't noticed that thread, sorry.
