### ISSUE TITLE
Yolo crashing during runtime

### ISSUE THREAD

**Issue by robotvin** [autowarefoundation/autoware_ai#950]
Hi
I have recently installed the yolo node.. and installed successfully..
During runtime it is crashing with Code 11 error... (memory leak) 

When i debugged the code... I found it crashing at following line.
line no 100 in yolo2.cpp - float *prediction = network_predict(darknet_network_, in_data); 

and one more i have observed the following function has been called with 12 arguments but it requires 13. 

line 108 in yolo2.cpp - get_region_boxes(output_layer, in_darknet_image.w, in_darknet_image.h,
							darknet_network_.w, darknet_network_.h,
							min_confidence_, darknet_box_scores_.data(), darknet_boxes_.data(),
0, 0, 0.5, 1); 

Kindly go through the code again.. suggest corrections...

Thanking you

**Comment by dejanpan** [comment]
We are trying to reproduce and debug your problem. And we can't do that if
you don't provide exact steps for when the error happens.
