### ISSUE TITLE
Cannot Launch node of Type [kitti_player/kitti_player], can't locate node [kitti_player]...

### ISSUE THREAD

**Issue by rongliu1996** [autowarefoundation/autoware_ai#992]
roslaunch kitti_launch kittiplayer.launch failed with error: Cannot Launch node of Type [kitti_player/kitti_player], can't locate node [kitti_player] in package [kitti_player].  Understand that it is the same issue as the original question in issue autowarefoundation/autoware_ai#935 but keen to know if ROS Kinetic is the cause of this issue and how to resolve it.  Many thanks in advance!

## Reproducing steps
  1.  followed instruction in https://github.com/CPFL/Autoware/tree/master/ros/src/util/packages/kitti_pkg;
  2.  rebuilt Autoware ./catkin_make_release
  3.  ran $ source ./devel/setup.bash under Autoware/ros
  4.  ran $ roslaunch kitti_launch kittiplayer.launch  under Autoware/ros

## Specifications

  - Ubuntu version:  16.4.1 LTS
  - ROS Version:  Kinetic
  - Autoware branch: master

**Comment by amc-nu** [comment]
@dejanpan I think it should work fine in Kinect. I’m not sure why it wasn’t included. @yk-fujii do you know the reason?

**Comment by yk-fujii** [comment]
Previously, kitti could not be compiled with kinetic.
It was resolved by the PR autowarefoundation/autoware#653.
however, we forgot to delete the if sentence, and It has been neglected until now.

https://github.com/CPFL/Autoware/pull/653

**Comment by amc-nu** [comment]
@yk-fujii thanks!
Checking further this node wasn’t updated to the new autoware_msgs. This would also be required.

**Comment by amc-nu** [comment]
Please check autowarefoundation/autoware_ai#1009

**Comment by amc-nu** [comment]
@shuzhenzhang Please check autowarefoundation/autoware_ai#1009
