### ISSUE TITLE
 catkin_make --pkg orb_localizer error

### ISSUE THREAD

**Issue by Hierom** [autowarefoundation/autoware_ai#996]

**Comment by sujiwo** [comment]
There are still some problems when compiling OpenCV 3.x. I'm still
investigating.

2017-10-19 12:29 GMT+09:00 Jerome <notifications@github.com>:

**Comment by sujiwo** [comment]
For ubuntu 14.04, it's best to stick with stock OpenCV 2.4.8 from
distribution.

2017-10-19 13:21 GMT+09:00 Jerome <notifications@github.com>:

**Comment by sujiwo** [comment]
Can you please give me full output of the catkin_make? like:

catkin_make --pkg orb_localizer > compile_out.log 2>&1



2017-10-25 22:38 GMT+09:00 Jerome <notifications@github.com>:

**Comment by sujiwo** [comment]
It looks like catkin was unable to find OpenCV library; did you install it
in non-standard path? If so, try adding it in CMAKE_PREFIX_PATH environment
variable.
For example, if OpenCV is in /usr/local/opencv2

export CMAKE_PREFIX_PATH=/usr/local/opencv2:$CMAKE_PREFIX_PATH
catkin_make --pkg orb_localizer

2017-10-26 11:02 GMT+09:00 Jerome <notifications@github.com>:

**Comment by Hierom** [comment]
@sujiwo  Many thanks! I change my CMAKE_PREFIX_PATH to /usr/local/include/opencv2
And the following was output in log.

[  0%] Built target DBoW2
[ 25%] Built target pangolin
Linking CXX executable /home/chienrong/Github/Autoware/ros/devel/lib/orb_localizer/imgprocx
[ 62%] Built target g2o
[ 62%] Built target std_msgs_generate_messages_py
[ 62%] Built target std_msgs_generate_messages_cpp
[ 62%] Built target std_msgs_generate_messages_lisp
[ 62%] Built target _orb_localizer_generate_messages_check_deps_debug
[ 75%] Built target orb_slam2
[ 75%] Built target orb_vocabulary
[ 75%] [ 75%] Built target orb_localizer_generate_messages_py
Built target orb_localizer_generate_messages_cpp
[ 75%] Built target orb_localizer_generate_messages_lisp
[ 87%] Built target orb_localizer_generate_messages_eus
[ 87%] Built target orb_mapping
[ 87%] Built target orb_mapping_offline
[ 87%] Built target orb_matching
[ 87%] Built target dumpmap
Scanning dependencies of target orb_localizer_generate_messages
[ 87%] Built target orb_localizer_generate_messages
[ 87%] Built target map_publisher
Scanning dependencies of target orb_matching_pf
CMakeFiles/imgprocx.dir/nodes/imgprocx/imgprocx.cpp.o: In function `main':
imgprocx.cpp:(.text.startup+0x9a6): undefined reference to `cv::imread(cv::String const&, int)'
imgprocx.cpp:(.text.startup+0x9ae): undefined reference to `cv::String::deallocate()'
imgprocx.cpp:(.text.startup+0xaec): undefined reference to `cv::String::allocate(unsigned long)'
imgprocx.cpp:(.text.startup+0xc08): undefined reference to `cv::String::deallocate()'
CMakeFiles/imgprocx.dir/nodes/imgprocx/ImagePreprocessor.cpp.o: In function `ImagePreprocessor::setGamma(cv::Mat&, float, bool)':
ImagePreprocessor.cpp:(.text+0xe36): undefined reference to `cv::LUT(cv::_InputArray const&, cv::_InputArray const&, cv::_OutputArray const&)'
CMakeFiles/imgprocx.dir/nodes/imgprocx/ImagePreprocessor.cpp.o: In function `ImagePreprocessor::autoAdjustGammaRGB(cv::Mat&, std::vector<cv::Mat, std::allocator<cv::Mat> >&, cv::Mat)':
ImagePreprocessor.cpp:(.text+0x16f0): undefined reference to `cv::LUT(cv::_InputArray const&, cv::_InputArray const&, cv::_OutputArray const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [/home/chienrong/Github/Autoware/ros/devel/lib/orb_localizer/imgprocx] Error 1
make[1]: *** [computing/perception/localization/packages/orb_localizer/CMakeFiles/imgprocx.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] [100%] [100%] Building CXX object computing/perception/localization/packages/orb_localizer/CMakeFiles/orb_matching_pf.dir/nodes/orb_matching/FusionOdometry.cpp.o
Building CXX object computing/perception/localization/packages/orb_localizer/CMakeFiles/orb_matching_pf.dir/nodes/orb_matching/Matcher.cpp.o
Building CXX object computing/perception/localization/packages/orb_localizer/CMakeFiles/orb_matching_pf.dir/nodes/orb_matching/orb_matching_pf.cpp.o
[100%] Building CXX object computing/perception/localization/packages/orb_localizer/CMakeFiles/orb_matching_pf.dir/nodes/common.cpp.o
/home/chienrong/Github/Autoware/ros/src/computing/perception/localization/packages/orb_localizer/nodes/orb_matching/Matcher.cpp: In function ‘tf::Transform rotateAxes(const tf::Transform&, float, float, float)’:
/home/chienrong/Github/Autoware/ros/src/computing/perception/localization/packages/orb_localizer/nodes/orb_matching/Matcher.cpp:40:55: warning: ‘tf::Quaternion::Quaternion(const tfScalar&, const tfScalar&, const tfScalar&)’ is deprecated (declared at /opt/ros/indigo/include/tf/LinearMath/Quaternion.h:51) [-Wdeprecated-declarations]
  rotation.setRotation (tf::Quaternion(roll, pitch, yaw).normalize());
                                                       ^
/home/chienrong/Github/Autoware/ros/src/computing/perception/localization/packages/orb_localizer/nodes/orb_matching/Matcher.cpp: In static member function ‘static tf::Transform Matcher::localizeByReference(const tf::Transform&, const tf::Transform&, const tf::Transform&, const tf::Transform&, const tf::Transform&)’:
/home/chienrong/Github/Autoware/ros/src/computing/perception/localization/packages/orb_localizer/nodes/orb_matching/Matcher.cpp:408:57: warning: ‘tf::Quaternion::Quaternion(const tfScalar&, const tfScalar&, const tfScalar&)’ is deprecated (declared at /opt/ros/indigo/include/tf/LinearMath/Quaternion.h:51) [-Wdeprecated-declarations]
  flipAxes.setRotation (tf::Quaternion(M_PI/2, 0, -M_PI/2).normalize());
                                                         ^
Linking CXX executable /home/chienrong/Github/Autoware/ros/devel/lib/orb_localizer/orb_matching_pf
[100%] Built target orb_matching_pf
make: *** [all] Error 2
Base path: /home/chienrong/Github/Autoware/ros
Source space: /home/chienrong/Github/Autoware/ros/src
Build space: /home/chienrong/Github/Autoware/ros/build
Devel space: /home/chienrong/Github/Autoware/ros/devel
Install space: /home/chienrong/Github/Autoware/ros/install
####
#### Running command: "make cmake_check_build_system" in "/home/chienrong/Github/Autoware/ros/build"
####
####
#### Running command: "make -j4 -l4" in "/home/chienrong/Github/Autoware/ros/build/computing/perception/localization/packages/orb_localizer"
####
Invoking "make -j4 -l4" failed


This was the second time after I changed the OpenCV path in catkin_make log, but first time (also after I changed the OpenCV path) was stopped in 75%, 
but now can move on to 100% but stopped by orb_matching_pf.
Does it make sense for trying catkin_make several times to make some target successfully? Or it just passing it?

Thanks

**Comment by sujiwo** [comment]
Try set CMAKE_PREFIX_PATH to /usr/local
And sorry, trying catkin_make several times won't fix problem.

2017-10-26 11:33 GMT+09:00 Jerome <notifications@github.com>:

**Comment by sujiwo** [comment]
May I see output of this command ?

locate libopencv_core.so

2017-10-26 12:03 GMT+09:00 Jerome <notifications@github.com>:

**Comment by sujiwo** [comment]
And this one:

locate libopencv_highgui.so

2017-10-26 12:08 GMT+09:00 Adi Sujiwo <sujiwo@gmail.com>:

**Comment by sujiwo** [comment]
I've confirmed that OpenCV 2.4.8 compiles cleanly with orb_slam. There may
be other problems, though.

**Comment by wsung1** [comment]
@sujiwo Dear sujiwon, thanks for your support. I'm a newbie here, so please bear with me. According to talks here, you asked Hierom to do 'catkin_make --pkg orb_localizer' instead of './catkin_make_release'. Does it mean 'catkin_make --pkg orb_localizer' could substitute for './catkin_make_release'? In my case,  'catkin_make --pkg orb_localizer' resulted in no problem while building up; yet './catkin_make_release' was invoking error. My problem has been posted at autowarefoundation/autoware_ai#7.

**Comment by sujiwo** [comment]
catkin_make --pkg orb_localizer compiles only this package, not the whole
Autoware workspace as ./catkin_make_release does. So when the former
results in no error but the latter does, I think the error does not lie in
orb_localizer.

2018-01-07 19:43 GMT+09:00 wsung1 <notifications@github.com>:
